import logging
import pytest
from src.infrastructure.logging.rich_logger import RichConsoleLogger

def test_logger_methods_exist() -> None:
    """
    Verifies that the adapter physically implements the methods 
    required by the ILogger protocol. (Mypy enforces the signatures).
    """
    logger = RichConsoleLogger(level="DEBUG")
    
    assert hasattr(logger, "debug")
    assert hasattr(logger, "info")
    assert hasattr(logger, "warning")
    assert hasattr(logger, "error")

def test_logger_routes_messages(caplog: pytest.LogCaptureFixture) -> None:
    """
    Verifies that calling the adapter methods correctly routes the messages
    down into the underlying Python logging module with the correct severity.
    """
    # Intercept all logs generated by our specific engine logger
    caplog.set_level(logging.DEBUG, logger="pokemon_engine")
    
    logger = RichConsoleLogger(level="DEBUG")
    
    logger.debug("Test debug")
    logger.info("Test info")
    logger.warning("Test warning")
    logger.error("Test error")
    
    records = caplog.records
    assert len(records) == 4
    
    assert records[0].levelname == "DEBUG"
    assert records[0].message == "Test debug"
    
    assert records[1].levelname == "INFO"
    assert records[1].message == "Test info"
    
    assert records[2].levelname == "WARNING"
    assert records[2].message == "Test warning"
    
    assert records[3].levelname == "ERROR"
    assert records[3].message == "Test error"

def test_logger_respects_level(caplog: pytest.LogCaptureFixture) -> None:
    """
    Verifies that instantiating the logger with a specific threshold (WARNING)
    correctly filters out lower-severity messages (INFO, DEBUG).
    """
    # Ensure caplog itself doesn't filter things out prematurely
    caplog.set_level(logging.DEBUG, logger="pokemon_engine")
    
    # Initialize our adapter with a strict WARNING threshold
    logger = RichConsoleLogger(level="WARNING")
    
    logger.debug("This should be dropped")
    logger.info("This should be dropped")
    logger.warning("This should pass")
    logger.error("This should pass")
    
    records = caplog.records
    
    assert len(records) == 2
    assert records[0].levelname == "WARNING"
    assert records[1].levelname == "ERROR"
